name: CI (Linux)

on: [push, pull_request]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.88.0 # MSRV
          - stable
          - nightly
        suite:
          - name: neon-polling
            features: ntex/neon-polling,ntex/cookie,ntex/url,ntex/compress,ntex/openssl,ntex/rustls,ntex/ws
          - name: neon-uring
            features: ntex/neon-uring,ntex/cookie,ntex/url,ntex/compress,ntex/openssl,ntex/rustls,ntex/ws
          - name: tokio
            features: ntex/tokio,ntex/cookie,ntex/url,ntex/compress,ntex/openssl,ntex/rustls,ntex/ws
          - name: compio
            features: ntex/compio,ntex/cookie,ntex/url,ntex/compress,ntex/openssl,ntex/rustls,ntex/ws
        kind: [test, doc]

    name: ${{ matrix.version }} - ${{ matrix.suite.name }} - ${{ matrix.kind }} - x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@nextest

      - name: Install ${{ matrix.version }}
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.version }}-x86_64-unknown-linux-gnu

      - name: Generate Cargo.lock
        uses: actions-rs/cargo@v1
        with:
          command: generate-lockfile

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.8.2

      - name: Run ${{ matrix.kind }} (${{ matrix.suite.name }})
        timeout-minutes: 10
        run: |
          if [ "${{ matrix.kind }}" = "test" ]; then
            cargo nextest run --retries=3 --all --no-default-features --features="${{ matrix.suite.features }}"
          else
            cargo test --doc --all --no-default-features --features="${{ matrix.suite.features }}"
          fi
